<!DOCTYPE html>
<html <?php language_attributes(); ?> class="scroll-smooth">
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Poppins:wght@600;700;800&display=swap" rel="stylesheet">
    
    <?php wp_head(); ?>
    <style>
        .hero-clip { clip-path: polygon(0 0, 100% 0, 100% 85%, 50% 100%, 0 85%); }
        /* Updated Selector: This will now only affect the UL generated by WP, 
           not the button below it.
        */
        .mobile-menu-link a { color: #1e293b !important; }
    </style>
</head>
<body <?php body_class('font-sans text-slate-800 antialiased'); ?>>

<header x-data="{ mobileMenuOpen: false, scrolled: false }" 
        @scroll.window="scrolled = (window.pageYOffset > 50) ? true : false"
        class="fixed w-full top-0 z-50 transition-colors duration-500 ease-in-out py-4"
        :class="scrolled ? 'bg-white/90 backdrop-blur-xl shadow-sm border-slate-200/50' : 'bg-white/10 backdrop-blur-md border-white/10'">
    
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-10">
            
            <div class="flex-shrink-0 flex items-center">
                <a href="<?php echo home_url(); ?>" class="flex items-center gap-3 group">
                    <img src="<?php echo get_template_directory_uri(); ?>/assets/images/logo.png" 
                         alt="Nextur Logo" 
                         class="h-10 w-auto object-contain">
                    <span class="font-heading font-bold text-2xl tracking-tight text-slate-900">
                        NEXTUR
                    </span>
                </a>
            </div>

            <div class="hidden md:flex items-center">
                <div class="transition-colors duration-300 font-heading text-sm font-semibold tracking-wide mr-8"
                     :class="scrolled ? 'text-slate-600' : 'text-white drop-shadow-sm'">
                    <?php
                        wp_nav_menu(array(
                            'theme_location' => 'primary',
                            'container'      => false,
                            'menu_class'     => 'flex gap-8 list-none m-0 p-0 items-center',
                            'echo'           => true,
                            'depth'          => 1,
                        ));
                    ?>
                </div>
                <a href="<?php echo site_url('/contact'); ?>" 
                   :class="scrolled ? 'bg-brand text-white hover:bg-brand-dark border border-transparent' : 'bg-white/20 backdrop-blur-lg border border-white/30 text-white hover:bg-white/30'"
                   class="px-6 py-2 rounded-full font-bold text-sm transition shadow-lg hover:shadow-xl font-heading">
                    Hubungi Kami
                </a>
            </div>

            <div class="flex items-center md:hidden">
                <button @click="mobileMenuOpen = !mobileMenuOpen" type="button" 
                        class="focus:outline-none p-2 rounded-md transition-colors duration-300"
                        :class="scrolled ? 'text-slate-600' : 'text-white'">
                    <svg class="h-8 w-8" x-show="!mobileMenuOpen" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                    <svg class="h-8 w-8" x-show="mobileMenuOpen" fill="none" viewBox="0 0 24 24" stroke="currentColor" style="display: none;">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div x-show="mobileMenuOpen" 
         x-transition:enter="transition ease-out duration-200"
         x-transition:enter-start="opacity-0 -translate-y-2"
         x-transition:enter-end="opacity-100 translate-y-0"
         x-transition:leave="transition ease-in duration-150"
         class="md:hidden bg-white border-b border-slate-100 absolute top-full left-0 w-full shadow-xl text-slate-800" style="display: none;">
        
        <div class="px-4 pt-4 pb-8 space-y-1">
            <?php
                wp_nav_menu(array(
                    'theme_location' => 'primary',
                    'container'      => false,
                    // Added 'mobile-menu-link' HERE so it only targets the menu items
                    'menu_class'     => 'flex flex-col space-y-4 font-heading font-semibold text-lg list-none m-0 p-0 mobile-menu-link',
                    'echo'           => true,
                ));
            ?>
             <div class="pt-6 mt-4 border-t border-slate-100">
                <a href="<?php echo site_url('/contact'); ?>" class="block w-full text-center px-6 py-3 bg-brand !text-white font-bold rounded-xl shadow-md">
                    Hubungi Kami
                </a>
            </div>
        </div>
    </div>
</header>